Apprendre/Models/DataBase/Card.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace Apprendre.Models
{
  public class Card : ICard
  {
    public int Id { get; set; }

    [Required]
    public Dictionary Dictionary { get; set; }
    public int DictionaryId { get; set; }

    [Required]
    [StringLength(100)]
    public string Word { get; set; }

    [Required]
    [StringLength(200)]
    public string Translation { get; set; }

    [StringLength(100)]
    public string Transcription { get; set; }

    [StringLength(500)]
    public string Example { get; set; }

    public List<Result> Results { get; set; }

    public List<Skip> Skips { get; set; }


    public List<Mark> Marks { get; set; }
  }
}

Apprendre/Controllers/CardsController.cs
using Apprendre.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Apprendre.Filters;

namespace Apprendre.Controllers
{
  [Authorize(Roles = "moderator")]
  public class CardsController : BaseController
  {
    private ICardService CardSV;

    public CardsController(ICardService cs)
    {
      CardSV = cs;
    }

    [SetCurDicStat]
    public ActionResult Edit(int id)
    {
      Card card = CardSV.Get(id);
      if (card == null) return HttpNotFound("Invalid id");
      return View(card);
    }

    public PartialViewResult EditContainer(Card card)
    {
      return PartialView(card);
    }

    [HttpPost]
    public string Edit(CardEditVM card)
    {
      if (ModelState.IsValid)
      {
        if (CardSV.Update(card, User.Identity.Name)) return HtmlUtils.Successful;
      }
      return HtmlUtils.Error;
    }

    [SetCurDicStat]
    public ActionResult Marked()
    {
      var marked = CardSV.GetMarked();
      return View(marked);
    }

    [SetCurDicStat]
    public ActionResult Add(int? id, int? added)
    {
      ViewBag.Added = added;

      int selected = id ?? -1;

      var dics = CardSV.GetAvailableDictionaries();
      var selDics = dics.Select(x => new SelectListItem() { Text = x.Name, 
        Value = x.Id.ToString(), Selected = x.Id == selected }).ToList();
      return View(selDics);
    }

    [HttpPost]
    public ActionResult Add(int dicId, string cardsContent)
    {
      if (string.IsNullOrWhiteSpace(cardsContent))
        return View("Error", new ErrorVM(Resources.Resource.eContentIsEmpty));

      var added = CardSV.AddCards(dicId, cardsContent);
      if (added == -1) 
        return View("Error", new ErrorVM("invalid dictionary id"));

      else if (added == 0) 
        return View("Error", new ErrorVM(Resources.Resource.eContentIsEmpty));

      return RedirectToAction("Add", "Cards", new { added = added, Id = dicId });
    }

    [AllowAnonymous]
    [SetCurDicStat]
    public ActionResult View(int id)
    {
      var card = CardSV.Get(id);
      if (card == null) return HttpNotFound("Invalid id");
      return View(card);
    }

    
         
    [HttpPost]
    public string Delete(int id)
    {
      bool result = CardSV.Delete(id);
      return result ? HtmlUtils.Successful : HtmlUtils.Error;
    }


    [Authorize(Roles = "user")]
    [HttpPost]
    public string Mark(int cardId)
    {
      bool result = CardSV.Mark(cardId, User.Identity.Name);
      return result ? HtmlUtils.Successful : HtmlUtils.Error;
    }
    
    
    [HttpPost]
    public ActionResult Unmark()
    {
      CardSV.UnmarkAll();
      return Redirect(Request.UrlReferrer.ToString());
    }

    [HttpPost]
    public JsonResult Search(int dicId, string text)
    {
      IEnumerable<Card> Cards = CardSV.Search(dicId, text);
      return Json(Cards);
    }
  }
}

Apprendre/Controllers/DictionariesController.cs
using Apprendre.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Text;
using System.Web.Hosting;
using Apprendre.Filters;

namespace Apprendre.Controllers
{
  public class DictionariesController : BaseController
  {
    private IDictionaryService DicSV;

    public DictionariesController(IDictionaryService ds)
    {
      DicSV = ds;
    }

    [SetCurDicStat]
    public ActionResult List()
    {
      var allDictionaries = DicSV.GetAllDictionariesVM();
      return View(allDictionaries);      
    }

    [SetCurDicStat]
    public ActionResult View(DictionaryRV rv, int? added)
    {
      ViewBag.Added = added;

      int pageSize = 100;
      DictionaryVM vm = DicSV.GetDictionary(rv, pageSize);

      if (vm == null) return RedirectToAction("List");
      return View(vm);      
    }

    [Authorize(Roles = "moderator")]
    [SetCurDicStat]
    public ActionResult Add(int? added)
    {
      ViewBag.Added = added;
      ViewBag.Languages = DicSV.GetAllDicLanguages();
      return View();
    }

    [HttpPost]
    [Authorize(Roles = "moderator")]
    public ActionResult Add(DictionaryAddVM dictionary)
    {
      if (!ModelState.IsValid) return View(dictionary);

      int dicId = DicSV.Add(dictionary, CurrentUser.Id, out int added);
      if (dicId == -1)
      {
        ModelState.AddModelError("", Resources.Resource.eDictionaryAlreadyExists);
        return View(dictionary);
      }
      
      return RedirectToAction("View", new { id = dicId, added = added });
    }

    [HttpPost]
    [Authorize(Roles = "admin")]
    public string Delete(int id)
    {
      bool isSuccessful = DicSV.Delete(id);
      return isSuccessful ? HtmlUtils.Successful : HtmlUtils.Error;
    }
    
    [HttpPost]
    [Authorize(Roles = "moderator")]
    public string Edit(DictionaryEditVM dictionary)
    {
      if (ModelState.IsValid)
      {
        var result = DicSV.Edit(dictionary);
        if (result) return HtmlUtils.Successful;
      }      
      return HtmlUtils.Error;      
    }

  }
}

Apprendre/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using Apprendre.Models;
using System.Data.Entity;
using System.Web.Script.Serialization;
using Apprendre.Resources;
using Microsoft.AspNet.Identity.Owin;
using Apprendre.Filters;
using System.Threading;
using System.Collections;

namespace Apprendre.Controllers
{
  public class UserController : BaseController
  {
    public UserController(
      IUserService us, ICoreService cs, IDictionaryService ds, IStatService ss)
    {
      CoreSV = cs;
      UserSV = us;
      DictionarySV = ds;
      StatSV = ss;
    }
    private IUserService UserSV;
    private IDictionaryService DictionarySV;
    private ICoreService CoreSV;
    private IStatService StatSV;

    private readonly double ServerTimezone = double.Parse(System.Configuration.ConfigurationManager.AppSettings["ServerTimezone"]);

    private AppUserManager _userManager;
    private AppUserManager UserManager
    {
      get
      {
        if (_userManager == null)
        {
          _userManager = new AppUserManager(new AppUserStore(new AppContext()));
          var provider = new MachineKeyProtectionProvider();
          UserManager.UserTokenProvider = new DataProtectorTokenProvider<AppUser, int>(provider.Create("ResetPasswordPurpose"));
        }
        return _userManager;
      }
    }

    [SetCurDicStat]
    public ActionResult View(int? id, Message? message)
    {
      if (!id.HasValue && !User.Identity.IsAuthenticated)
        return RedirectHome();

      ViewBag.Message =
           message == Message.ConfirmEmailSuccess ? Resource.uConfirmEmailSuccess
         : message == Message.StatisticsDeletedSuccess ? Resource.uStatisticsDeleted
         : "";

      int userId = id ?? User.Identity.GetUserId<int>();
      AppUser pageUser = UserManager.Users.Include(x => x.CurrentDictionary).FirstOrDefault(x => x.Id == userId);
      if (pageUser == null) return RedirectHome();

      Mode firstMode = pageUser.GetFirstMode();
      var SumStat = CoreSV.GetSumStat(pageUser);
      var CurDicStat = SumStat.FirstOrDefault(x => x.DicId == firstMode.DicId && x.IsDirect == firstMode.IsDirect);

      UserVM VM = new UserVM()
      {
        AppUser = pageUser,
        UserId = pageUser.Id,
        UserName = pageUser.UserName,
        SumStat = SumStat,
        CurDicStat = CurDicStat,
        DicId = CurDicStat.DicId,
        DicName = CurDicStat.DicName,
        IsDirect = CurDicStat.IsDirect
      };

      IEnumerable<Dictionary> dictionaries = DictionarySV.GetAllDictionaries();
      VM.Dictionaries = dictionaries.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == pageUser.CurrentDictionary.Id }).OrderBy(x => x.Text).ToList();

      VM.IsOwner = userId == User.Identity.GetUserId<int>();
      if (VM.IsOwner)
      {
        VM.CurrentModeSettings = UserSV.GetModeSettings(userId, pageUser.CurrentDictionary.Id, pageUser.CurrentIsDirect);

        VM.MixedModeList = UserSV.GetMixedModeSettings(pageUser.Id);
      }

      if (User.IsInRole("admin"))
      {
        VM.LastResults = StatSV.GetLastResults(userId, 20);

        foreach (var r in VM.LastResults)
          r.ToLocalTime(CurrentUser.Timezone, ServerTimezone);

        VM.MaxCntResults = StatSV.GetMaxCntResults(userId, 20);

        foreach (var r in VM.MaxCntResults)
          r.ToLocalTime(CurrentUser.Timezone, ServerTimezone);
      }
      return View(VM);
    }


    [SetCurDicStat]
    public ActionResult Stat(int id, int dicId, bool isDirect)
    {
      AppUser pageUser = UserManager.Users.Include(x => x.CurrentDictionary).FirstOrDefault(x => x.Id == id);
      if (pageUser == null) return RedirectHome();

     
      if (!DictionarySV.Exists(dicId)) return RedirectHome();
      DicStat ds = CoreSV.GetDicStat(id, new Mode(dicId, isDirect));

      double[][] strengthRanksData = StatSV.GetStrengthRanksData(id, dicId, isDirect);
      string json = new JavaScriptSerializer().Serialize(strengthRanksData);

      string daysData = StatSV.GetDaysData(id, dicId, isDirect);

      var weakResults = StatSV.GetWeakestResults(id, dicId, isDirect, 30);

      UserStatVM VM = new UserStatVM
      {
        UserId = id,
        UserName = pageUser.UserName,
        DicId = ds.DicId,
        DicName = ds.DicName,
        IsDirect = ds.IsDirect,
        DicStat = ds,
        RanksData = json,
        DaysData = daysData,
        WeakResults = weakResults, 
        IsOwner = id == CurrentUser.Id
      };
      return View("Stat", VM);
     
    }


    [Authorize]
    [SetCurDicStat]
    public ActionResult Dictionary(UserDictionaryRV rv)
    {
      if (CurrentUser.Id != rv.Id && !User.IsInRole("moderator"))
      {
        return RedirectToAction("View", new { Id = rv.Id });
      }

      int pageSize = 100;
      var dicResultsVM = StatSV.GetDicResults(rv, pageSize);
      dicResultsVM.IsOwner = rv.Id == CurrentUser.Id;
      return View(dicResultsVM);
    }

    [HttpPost]
    public string SkipCard(int cardId, bool isDirect, bool skip)
    {
      return StatSV.SkipCard(CurrentUser.Id, cardId, isDirect, skip) ?
        HtmlUtils.Successful : HtmlUtils.Error;
    }






    //
    // SETTINGS & MODE
    //

    public enum Message
    {
      ChangePasswordSuccess,
      WrongOldPasswordError,
      ChangeEmailSuccess,
      ChangeEmailError,
      ConfirmEmailSuccess,
      StatisticsDeletedSuccess
    }

    [Authorize]
    [SetCurDicStat]
    public ActionResult Settings(Message? message)
    {
      ViewBag.Message =
            message == Message.ChangePasswordSuccess ? Resource.uPasswordChanged
          : message == Message.WrongOldPasswordError ? Resource.uWrongOldPassword
          : message == Message.ChangeEmailSuccess ? Resource.uEmailChanged
          : message == Message.ChangeEmailError ? Resource.uChangeEmailError
          : message == Message.ConfirmEmailSuccess ? Resource.uConfirmEmailSuccess
          : "";

      string Language = Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName;
      ViewBag.languagesSL = SiteLanguages.List.Select(x => new SelectListItem() { Value = x.Code, Text = x.SelfName, Selected = x.Code == Language });


      ViewBag.timezonesSL = Enumerable.Range(-12, 27).Select(x => new SelectListItem
      {
        Value = x.ToString(),
        Text = "UTC" + (x >= 0 ? "+" : "") + x,
        Selected = x == CurrentUser.Timezone
      });

      var model = new SettingsVM() 
      {
        Email = CurrentUser.Email, 
        Timezone = CurrentUser.Timezone, 
        Language = CurrentUser.Language 
      };
      return View(model);
    }

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> ChangeSettings(SettingsVM model)
    {
      object RouteValues = null;
      if (ModelState.IsValid)
      {
        if (CurrentUser.Email != model.Email)
        {
          await SendConfirmation(CurrentUser);
          RouteValues = new { Message = Message.ChangeEmailSuccess };
        }       

        if (SiteLanguages.List.Any(x => x.Code == model.Language))
          SetLanguageCookie(model.Language);
        else model.Language = null;

        UserSV.ChangeSettings(CurrentUser.Id, 
          model.Email, 
          model.Timezone, 
          model.Language);

        SetFontSizeCookie(model.FontSize);
      }
      return RedirectToAction("Settings", RouteValues);
    }

    private void SetFontSizeCookie(int? fontSize)
    {
      HttpCookie cookie = Request.Cookies["fontSize"];

      if (fontSize == null || fontSize.Value <= 10 || fontSize.Value == 100 || fontSize > 1000)
      {
        if (cookie != null) cookie.Expires = DateTime.Now.AddYears(-1);
      }
      else
      {
        if (cookie != null) cookie.Value = fontSize.ToString();
        else
        {
          cookie = new HttpCookie("fontSize", fontSize.ToString())
          {
            HttpOnly = false,
            Expires = DateTime.Now.AddYears(3)
          };
        }
      }
      if (cookie != null) Response.Cookies.Add(cookie);
    }

    private void SetLanguageCookie(string language)
    {
      SetCookie("language", language);
    }


    [Authorize]
    [HttpPost]
    public JsonResult GetModeSettings(int dicId, bool isDirect)
    {
      ModeSetting dus = UserSV.GetModeSettings(CurrentUser.Id, dicId, isDirect);

      var obj = new { dus.StudyLimit, dus.RandomOrder };
      return Json(obj);
    }

    [Authorize]
    [HttpPost]
    public ActionResult ChangeMode(int dicId, bool isDirect, bool? needRedirect, int? limit, bool? randomOrder)
    {
      if (DictionarySV.Exists(dicId) == false || 
        UserSV.ChangeMode(CurrentUser.Id, dicId, isDirect, limit, randomOrder) == false)
      {
        return new ContentResult() { Content = HtmlUtils.Error };
      }
        
      if (needRedirect == true)
        return new ContentResult() { Content = HtmlUtils.Successful };

      return Redirect(Request.UrlReferrer.ToString());
    }


    [Authorize]
    [HttpPost]
    public string ChangeMixedMode(ModeSettingEditVM[] modes)
    {
      if (modes == null 
        || DictionarySV.Exists(modes.Select(x => x.DicId)) == false 
        || UserSV.ChangeMixedMode(CurrentUser.Id, modes) == false)
      {
        return HtmlUtils.Error;
      }
      return HtmlUtils.Successful;
    }

    [Authorize]
    [HttpPost]
    public string SwitchToMixedMode()
    {
      if (!UserSV.SwitchToMixedMode(CurrentUser.Id))
      {
        return HtmlUtils.Error;
      }
      return HtmlUtils.Successful;
    }














    //
    // AUTHORIZATION
    //

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> ChangePassword(ChangePasswordVM model)
    {

Apprendre/Views/Cards/Add.cshtml
@model IEnumerable<SelectListItem>
@{
  ViewBag.Title = Resource.eAddCards;
  SelectListItem current = Model.FirstOrDefault(x => x.Selected == true);
}

@{ViewBag.Type = "addCards";}
@Html.Partial("_DicNav")

<div class="form-width-limit">
  <h1>@ViewBag.Title</h1>
  @if (ViewBag.Added != null)
  {
    <div class="green">
      @Resource.eWordsAdded: @ViewBag.Added
    </div>
    <div class="margin-10">
      @if (current != null)
      {
        @Html.ActionLink(Resource.eToDictionary + " " + current.Text, "View", "Dictionaries", new { id = current.Value }, new { @class = "rounded-link" })
      }
    </div>
  }
  @using (Html.BeginForm("Add", "Cards", FormMethod.Post, new { @class = "editor" }))
  {
    <div>
      <span class="inline margin-5">@Resource.eAddToDictionary</span>
      @Html.DropDownList("dicId", Model)
    </div>
    <br />
    <textarea id="cards-content" class="edit-field" name="cardsContent" placeholder="@Html.Raw(Resource.eAddWordsFormat)" ></textarea>
    <input type="submit" value="@Resource._Add" class="but">
  }
</div>

Apprendre/Views/Cards/Edit.cshtml
@model Card
@{
  ViewBag.Title = Resource.eEditCard;
}

<div class="form-width-limit">
  <h1>@ViewBag.Title</h1>
  @Html.ActionLink("← " + Resource.eBackToDictionary + " " + Model.Dictionary.Name, "View", "Dictionaries", new { Id = Model.Dictionary.Id }, new { @class = "rounded-link" })

  @Html.Partial("EditContainer")
</div> 

Apprendre/Views/Cards/EditContainer.cshtml
@model Card

@using (Html.BeginForm("Edit", "Cards", FormMethod.Post,
  new { Id = "form-edit-result", @class = "editor" }))
{
  @Html.HiddenFor(m => m.Id)

  @Html.LabelFor(x => x.Word, Resource._Word)
  <div contenteditable="true" id="Word" class="editor-box">@Model.Word</div>

  @Html.LabelFor(x => x.Transcription, Resource._Transcription)
  <div contenteditable="true" id="Transcription" class="editor-box">@Model.Transcription</div>

  @Html.LabelFor(x => x.Translation, Resource._Translation)
  <div contenteditable="true" id="Translation" class="editor-box">@Model.Translation</div>

  @Html.LabelFor(x => x.Example, Resource._Example)
  @Html.TextAreaFor(x => x.Example)

  <div class="align-left">
    @Html.CheckBox("Marked")
    @Html.Label("Marked", Resource.eMarkForChecking, new { style = "display: inline-block" })
  </div>
}
<button id="button-save-card"
        class="margin-15 but"
        data-val1="@Resource._Save"
        data-val2="@Resource._Saved">
  @Resource._Save
</button>

<button id="button-delete-card"
        class="margin-15 but"
        data-val1="@Resource._Delete"
        data-val2="@Resource._Deleted">
  @Resource._Delete
</button>

Apprendre/Views/Cards/Marked.cshtml
@model IEnumerable<Mark>
@{
  ViewBag.Title = Resource.eCardsForChecking;
  int count = 1;
}


@{ViewBag.Type = "marked";}
@Html.Partial("_DicNav")

<h1>@ViewBag.Title</h1>

<form method="post" action="/cards/unmark">
  <input type="submit" class="but" value="@Resource.eClearTheList">
</form>
<div class="x-scroll">
  <table class='solid-table'>
    <tr>
      <th>@Resource._NumberSign</th>
      <th>@Resource._Word</th>
      <th>@Resource._Translation</th>
      <th>@Resource._Dictionary</th>
      <th>@Resource._User</th>
    </tr>

    @foreach (var mark in Model)
    {
      <tr>
        <td>@Html.ActionLink((count++).ToString(), "Edit", "Cards", new { Id = mark.Card.Id }, null)</td>
        <td>
          @mark.Card.Word
          @if (mark.Card.Transcription != null)
          {<text>@mark.Card.Transcription</text>}
        </td>
        <td>@mark.Card.Translation</td>
        <td>
          @Html.ActionLink(mark.Card.Dictionary.Name, "View", "Dictionaries", new { Id = mark.Card.Dictionary.Id }, null)
        </td>
        <td>
          @Html.ActionLink(mark.User.UserName, "View", "User", new { Id = mark.User.Id }, null)
        </td>
      </tr>
    }
  </table>
</div>

Apprendre/Views/Cards/View.cshtml
@model Card

@{
    ViewBag.Title = Resource.eViewCard;
}

<h1>@ViewBag.Title</h1>

@Html.ActionLink("← " + Resource.eBackToDictionary + " " + Model.Dictionary.Name, "View", "Dictionaries", new { Id = Model.Dictionary.Id }, new { @class = "rounded-link" })

<div class="form-width-limit editor">

  @Html.LabelFor(x => x.Word, Resource._Word)
  <div class="editor-box">@Model.Word</div>

  @Html.LabelFor(x => x.Transcription, Resource._Transcription)
  <div class="editor-box">@(Model.Transcription != null ? @Model.Transcription : " ")</div>

  @Html.LabelFor(x => x.Translation, Resource._Translation)
  <div class="editor-box">@Model.Translation</div>

  @Html.LabelFor(x => x.Example, Resource._Example)
  <div class="editor-box" id="edit-example">@(Model.Example != null ? @Model.Example : " ")</div>
</div>