Apprendre/Models/DataBase/Dictionary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Apprendre.Models
{
  public class Dictionary : IDictionary
  {
    public int Id { get; set; }

    [Required]
    [StringLength(70)]
    [DataType(DataType.Text)]
    public string Name { get; set; }
    public List<Card> Cards { get; set; }

    [Required]
    public AppUser Author { get; set; }
    public int AuthorId { get; set; }

    public bool IsPublic { get; set; }
    public string WordLanguage { get; set; }
    public string TranslationLanguage { get; set; }
    public bool ChooseExerciseAvailable { get; set; }
  }
}

Apprendre/Controllers/DictionariesController.cs
using Apprendre.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Text;
using System.Web.Hosting;
using Apprendre.Filters;

namespace Apprendre.Controllers
{
  public class DictionariesController : BaseController
  {
    private IDictionaryService DicSV;

    public DictionariesController(IDictionaryService ds)
    {
      DicSV = ds;
    }

    [SetCurDicStat]
    public ActionResult List()
    {
      var allDictionaries = DicSV.GetAllDictionariesVM();
      return View(allDictionaries);      
    }

    [SetCurDicStat]
    public ActionResult View(DictionaryRV rv, int? added)
    {
      ViewBag.Added = added;

      int pageSize = 100;
      DictionaryVM vm = DicSV.GetDictionary(rv, pageSize);

      if (vm == null) return RedirectToAction("List");
      return View(vm);      
    }

    [Authorize(Roles = "moderator")]
    [SetCurDicStat]
    public ActionResult Add(int? added)
    {
      ViewBag.Added = added;
      ViewBag.Languages = DicSV.GetAllDicLanguages();
      return View();
    }

    [HttpPost]
    [Authorize(Roles = "moderator")]
    public ActionResult Add(DictionaryAddVM dictionary)
    {
      if (!ModelState.IsValid) return View(dictionary);

      int dicId = DicSV.Add(dictionary, CurrentUser.Id, out int added);
      if (dicId == -1)
      {
        ModelState.AddModelError("", Resources.Resource.eDictionaryAlreadyExists);
        return View(dictionary);
      }
      
      return RedirectToAction("View", new { id = dicId, added = added });
    }

    [HttpPost]
    [Authorize(Roles = "admin")]
    public string Delete(int id)
    {
      bool isSuccessful = DicSV.Delete(id);
      return isSuccessful ? HtmlUtils.Successful : HtmlUtils.Error;
    }
    
    [HttpPost]
    [Authorize(Roles = "moderator")]
    public string Edit(DictionaryEditVM dictionary)
    {
      if (ModelState.IsValid)
      {
        var result = DicSV.Edit(dictionary);
        if (result) return HtmlUtils.Successful;
      }      
      return HtmlUtils.Error;      
    }

  }
}

Apprendre/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Apprendre.Models;
using System.Web.UI.WebControls;
using System.Diagnostics;
using Apprendre.Filters;

namespace Apprendre.Controllers
{
  [Authorize(Roles="moderator")]
  public class ResultsController : BaseController
  {
    IResultService ResultSV;
    public ResultsController(IResultService rs)
    {
      ResultSV = rs;
    }

    private readonly double ServerTimezone = double.Parse(System.Configuration.ConfigurationManager.AppSettings["ServerTimezone"]);

    [Authorize(Roles = "admin")]
    [SetCurDicStat]
    public ActionResult Edit(int Id)
    {
      Result result = ResultSV.GetResult(Id);
      if (result == null) return RedirectHome();

      result.ToLocalTime(CurrentUser.Timezone, ServerTimezone);
      return View(result);
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public string Edit(ResultEditVM Result)
    {
      if (ModelState.IsValid)
      {
        Result.ToServerTime(CurrentUser.Timezone, ServerTimezone);
        bool isSuccessful = ResultSV.Update(Result);
        if (isSuccessful) return HtmlUtils.Successful;
      }
      return HtmlUtils.Error;
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public string Delete(int Id)
    {
      return ResultSV.Delete(Id) ? HtmlUtils.Successful : HtmlUtils.Error;
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public ActionResult DeleteAll(int UserId, int DicId, bool IsDirect)
    {
      ResultSV.DeleteAll(UserId, DicId, IsDirect);

      return RedirectToAction("View", "User", new { Id = UserId, dic = DicId, isDirect = IsDirect, Message = UserController.Message.StatisticsDeletedSuccess });
    }




    [SetCurDicStat]
    public ActionResult View(ResultsRV rv)
    {
      int pageSize = 100;
      var vm = ResultSV.GetResults(rv, pageSize);
      foreach (var r in vm.Results)
        r.ToLocalTime(CurrentUser.Timezone, ServerTimezone);
      return View(vm);
    }

    [SetCurDicStat]
    public ActionResult Nulls()
    {
      return RedirectToAction("View", new ResultsRV { OnlyNulls = true });
    }

    [SetCurDicStat]
    public ActionResult Reset()
    {
      int[] cnt = ResultSV.ResetDateTime();
      return View("Error", new ErrorVM(string.Format("removed {0} null results, reset date in {1} results", cnt[0], cnt[1])));
    }


    [AllowAnonymous]
    public ActionResult Guest(ResultsRV rv)
    {
      var results = Session["results"] as List<Result>;
      if (results == null) results = new List<Result>();
      int pageSize = 100;

      ResultsVM vm = new ResultsVM()
      {
        RouteValues = rv,
        PageInfo = new PageInfo(1, pageSize, results.Count),
        Results = results.ToArray()
      };
            
      return View("View", vm);
    }

  }
}

Apprendre/Controllers/StudyController.cs
using Apprendre.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Apprendre.Filters;
using Apprendre.Resources;

namespace Apprendre.Controllers
{
  
  public class StudyController : BaseController
  {
    private IDictionaryService DicSV;

    public StudyController(IDictionaryService ds)
    {
      DicSV = ds;
    }

    [SetCurDicStat]
    public ActionResult Main(string Message, int? Try)
    {
      ViewBag.IsMain = true;

      if (Try.HasValue) ViewBag.DicTrySet = true;

      if (Session["ConfirmationSent"] as bool? == true)
      {
        ViewBag.Message = Resource.uConfirmationSent;
        Session["ConfirmationSent"] = null;
      }
      
      StudyVM vm = new StudyVM()
      {
        IsAuthenticated = User.Identity.IsAuthenticated,
        Training2Available = true,
        IsDicTrySet = Try.HasValue
      };

      if (ViewBag.CurDicStat is DicStat CurDicStat 
        && !CurDicStat.IsInMix
        && (!CurDicStat.DicChooseAvailable || CurDicStat.Studied < 10))
        vm.Training2Available = false;

      if (!User.Identity.IsAuthenticated)
      {
        int defaultDicId = 2;
        if (Try.HasValue)
        {
          var cookie = Request.Cookies.Get("guestdic");
          if (cookie != null) int.TryParse(cookie.Value, out defaultDicId);
          defaultDicId = Try.Value;
          SetCookie("guestdic", Try.Value.ToString());
        }
        vm.Dictionaries = DicSV.GetAllDictionaries().Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == defaultDicId }).OrderBy(x => x.Text).ToList();
      }     
      return View(vm);
    }

  }
}

Apprendre/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using Apprendre.Models;
using System.Data.Entity;
using System.Web.Script.Serialization;
using Apprendre.Resources;
using Microsoft.AspNet.Identity.Owin;
using Apprendre.Filters;
using System.Threading;
using System.Collections;

namespace Apprendre.Controllers
{
  public class UserController : BaseController
  {
    public UserController(
      IUserService us, ICoreService cs, IDictionaryService ds, IStatService ss)
    {
      CoreSV = cs;
      UserSV = us;
      DictionarySV = ds;
      StatSV = ss;
    }
    private IUserService UserSV;
    private IDictionaryService DictionarySV;
    private ICoreService CoreSV;
    private IStatService StatSV;

    private readonly double ServerTimezone = double.Parse(System.Configuration.ConfigurationManager.AppSettings["ServerTimezone"]);

    private AppUserManager _userManager;
    private AppUserManager UserManager
    {
      get
      {
        if (_userManager == null)
        {
          _userManager = new AppUserManager(new AppUserStore(new AppContext()));
          var provider = new MachineKeyProtectionProvider();
          UserManager.UserTokenProvider = new DataProtectorTokenProvider<AppUser, int>(provider.Create("ResetPasswordPurpose"));
        }
        return _userManager;
      }
    }

    [SetCurDicStat]
    public ActionResult View(int? id, Message? message)
    {
      if (!id.HasValue && !User.Identity.IsAuthenticated)
        return RedirectHome();

      ViewBag.Message =
           message == Message.ConfirmEmailSuccess ? Resource.uConfirmEmailSuccess
         : message == Message.StatisticsDeletedSuccess ? Resource.uStatisticsDeleted
         : "";

      int userId = id ?? User.Identity.GetUserId<int>();
      AppUser pageUser = UserManager.Users.Include(x => x.CurrentDictionary).FirstOrDefault(x => x.Id == userId);
      if (pageUser == null) return RedirectHome();

      Mode firstMode = pageUser.GetFirstMode();
      var SumStat = CoreSV.GetSumStat(pageUser);
      var CurDicStat = SumStat.FirstOrDefault(x => x.DicId == firstMode.DicId && x.IsDirect == firstMode.IsDirect);

      UserVM VM = new UserVM()
      {
        AppUser = pageUser,
        UserId = pageUser.Id,
        UserName = pageUser.UserName,
        SumStat = SumStat,
        CurDicStat = CurDicStat,
        DicId = CurDicStat.DicId,
        DicName = CurDicStat.DicName,
        IsDirect = CurDicStat.IsDirect
      };

      IEnumerable<Dictionary> dictionaries = DictionarySV.GetAllDictionaries();
      VM.Dictionaries = dictionaries.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == pageUser.CurrentDictionary.Id }).OrderBy(x => x.Text).ToList();

      VM.IsOwner = userId == User.Identity.GetUserId<int>();
      if (VM.IsOwner)
      {
        VM.CurrentModeSettings = UserSV.GetModeSettings(userId, pageUser.CurrentDictionary.Id, pageUser.CurrentIsDirect);

        VM.MixedModeList = UserSV.GetMixedModeSettings(pageUser.Id);
      }

      if (User.IsInRole("admin"))
      {
        VM.LastResults = StatSV.GetLastResults(userId, 20);

        foreach (var r in VM.LastResults)
          r.ToLocalTime(CurrentUser.Timezone, ServerTimezone);

        VM.MaxCntResults = StatSV.GetMaxCntResults(userId, 20);

        foreach (var r in VM.MaxCntResults)
          r.ToLocalTime(CurrentUser.Timezone, ServerTimezone);
      }
      return View(VM);
    }


    [SetCurDicStat]
    public ActionResult Stat(int id, int dicId, bool isDirect)
    {
      AppUser pageUser = UserManager.Users.Include(x => x.CurrentDictionary).FirstOrDefault(x => x.Id == id);
      if (pageUser == null) return RedirectHome();

     
      if (!DictionarySV.Exists(dicId)) return RedirectHome();
      DicStat ds = CoreSV.GetDicStat(id, new Mode(dicId, isDirect));

      double[][] strengthRanksData = StatSV.GetStrengthRanksData(id, dicId, isDirect);
      string json = new JavaScriptSerializer().Serialize(strengthRanksData);

      string daysData = StatSV.GetDaysData(id, dicId, isDirect);

      var weakResults = StatSV.GetWeakestResults(id, dicId, isDirect, 30);

      UserStatVM VM = new UserStatVM
      {
        UserId = id,
        UserName = pageUser.UserName,
        DicId = ds.DicId,
        DicName = ds.DicName,
        IsDirect = ds.IsDirect,
        DicStat = ds,
        RanksData = json,
        DaysData = daysData,
        WeakResults = weakResults, 
        IsOwner = id == CurrentUser.Id
      };
      return View("Stat", VM);
     
    }


    [Authorize]
    [SetCurDicStat]
    public ActionResult Dictionary(UserDictionaryRV rv)
    {
      if (CurrentUser.Id != rv.Id && !User.IsInRole("moderator"))
      {
        return RedirectToAction("View", new { Id = rv.Id });
      }

      int pageSize = 100;
      var dicResultsVM = StatSV.GetDicResults(rv, pageSize);
      dicResultsVM.IsOwner = rv.Id == CurrentUser.Id;
      return View(dicResultsVM);
    }

    [HttpPost]
    public string SkipCard(int cardId, bool isDirect, bool skip)
    {
      return StatSV.SkipCard(CurrentUser.Id, cardId, isDirect, skip) ?
        HtmlUtils.Successful : HtmlUtils.Error;
    }






    //
    // SETTINGS & MODE
    //

    public enum Message
    {
      ChangePasswordSuccess,
      WrongOldPasswordError,
      ChangeEmailSuccess,
      ChangeEmailError,
      ConfirmEmailSuccess,
      StatisticsDeletedSuccess
    }

    [Authorize]
    [SetCurDicStat]
    public ActionResult Settings(Message? message)
    {
      ViewBag.Message =
            message == Message.ChangePasswordSuccess ? Resource.uPasswordChanged
          : message == Message.WrongOldPasswordError ? Resource.uWrongOldPassword
          : message == Message.ChangeEmailSuccess ? Resource.uEmailChanged
          : message == Message.ChangeEmailError ? Resource.uChangeEmailError
          : message == Message.ConfirmEmailSuccess ? Resource.uConfirmEmailSuccess
          : "";

      string Language = Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName;
      ViewBag.languagesSL = SiteLanguages.List.Select(x => new SelectListItem() { Value = x.Code, Text = x.SelfName, Selected = x.Code == Language });


      ViewBag.timezonesSL = Enumerable.Range(-12, 27).Select(x => new SelectListItem
      {
        Value = x.ToString(),
        Text = "UTC" + (x >= 0 ? "+" : "") + x,
        Selected = x == CurrentUser.Timezone
      });

      var model = new SettingsVM() 
      {
        Email = CurrentUser.Email, 
        Timezone = CurrentUser.Timezone, 
        Language = CurrentUser.Language 
      };
      return View(model);
    }

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> ChangeSettings(SettingsVM model)
    {
      object RouteValues = null;
      if (ModelState.IsValid)
      {
        if (CurrentUser.Email != model.Email)
        {
          await SendConfirmation(CurrentUser);
          RouteValues = new { Message = Message.ChangeEmailSuccess };
        }       

        if (SiteLanguages.List.Any(x => x.Code == model.Language))
          SetLanguageCookie(model.Language);
        else model.Language = null;

        UserSV.ChangeSettings(CurrentUser.Id, 
          model.Email, 
          model.Timezone, 
          model.Language);

        SetFontSizeCookie(model.FontSize);
      }
      return RedirectToAction("Settings", RouteValues);
    }

    private void SetFontSizeCookie(int? fontSize)
    {
      HttpCookie cookie = Request.Cookies["fontSize"];

      if (fontSize == null || fontSize.Value <= 10 || fontSize.Value == 100 || fontSize > 1000)
      {
        if (cookie != null) cookie.Expires = DateTime.Now.AddYears(-1);
      }
      else
      {
        if (cookie != null) cookie.Value = fontSize.ToString();
        else
        {
          cookie = new HttpCookie("fontSize", fontSize.ToString())
          {
            HttpOnly = false,
            Expires = DateTime.Now.AddYears(3)
          };
        }
      }
      if (cookie != null) Response.Cookies.Add(cookie);
    }

    private void SetLanguageCookie(string language)
    {
      SetCookie("language", language);
    }


    [Authorize]
    [HttpPost]
    public JsonResult GetModeSettings(int dicId, bool isDirect)
    {
      ModeSetting dus = UserSV.GetModeSettings(CurrentUser.Id, dicId, isDirect);

      var obj = new { dus.StudyLimit, dus.RandomOrder };
      return Json(obj);
    }

    [Authorize]
    [HttpPost]
    public ActionResult ChangeMode(int dicId, bool isDirect, bool? needRedirect, int? limit, bool? randomOrder)
    {
      if (DictionarySV.Exists(dicId) == false || 
        UserSV.ChangeMode(CurrentUser.Id, dicId, isDirect, limit, randomOrder) == false)
      {
        return new ContentResult() { Content = HtmlUtils.Error };
      }
        
      if (needRedirect == true)
        return new ContentResult() { Content = HtmlUtils.Successful };

      return Redirect(Request.UrlReferrer.ToString());
    }


    [Authorize]
    [HttpPost]
    public string ChangeMixedMode(ModeSettingEditVM[] modes)
    {
      if (modes == null 
        || DictionarySV.Exists(modes.Select(x => x.DicId)) == false 
        || UserSV.ChangeMixedMode(CurrentUser.Id, modes) == false)
      {
        return HtmlUtils.Error;
      }
      return HtmlUtils.Successful;
    }

    [Authorize]
    [HttpPost]
    public string SwitchToMixedMode()
    {
      if (!UserSV.SwitchToMixedMode(CurrentUser.Id))
      {
        return HtmlUtils.Error;
      }
      return HtmlUtils.Successful;
    }














    //
    // AUTHORIZATION
    //

    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> ChangePassword(ChangePasswordVM model)
    {

Apprendre/Views/User/All_Users.cshtml
@model IEnumerable<AppUserVM>
@{
  ViewBag.Title = @Resource.uAllUsers;
}

<h1>@ViewBag.Title</h1>
<div class="x-scroll">
  <table id="all-users" class='solid-table'>

    <tr>
      <th>@Resource._NumberSign</th>
      <th>@Resource._UserName</th>
      <th>@Resource._Email</th>
      <th>@Resource.uEmailConfirmed</th>
      <th>@Resource.pSiteLanguage</th>
      <th>@Resource.pModeForStudying</th>
      <th>@Resource.uRoles</th>
      <th>@Resource.uLastActivity</th>
    </tr>

    @foreach (var u in Model)
    {
      bool empty = true;
      <tr>
        <td>@Html.ActionLink(u.AppUser.Id.ToString(), "View", "User", new { Id = u.AppUser.Id }, null)</td>
        <td>@u.AppUser.UserName</td>
        <td>@u.AppUser.Email</td>
        <td>@(u.AppUser.EmailConfirmed ? "✓" : "-")</td>
        <td>@u.AppUser.Language</td>
        <td>
          @foreach (var m in u.CurrentModes)
          {
            if (!empty) {<text>, </text> }
            else { empty = false; }
            @Html.ActionLink(m.DicName + (m.IsDirect? "" : "↓"), "View", "Dictionaries", new { Id = m.DicId }, null)
          }
        </td>
        <td>@string.Join(", ", u.Roles)</td>
        <td class="date-col">@u.AppUser.LastActivity</td>
      </tr>
    }
  </table>
</div>

Apprendre/Views/User/Dictionary.cshtml
@model UserDictionaryVM

@{
  ViewBag.Title = Resource.pSelectCards + " " + Model.DicName + ", " + (Model.IsDirect ? Resource._DirectDirection : Resource._InverseDirection);

  ViewBag.Type = "dictionary";
  var rv = Model.RouteValues;
}

@Html.Partial("_UserNav")

<h2>
  @Resource.pSelectCards
  @Html.ActionLink(Model.DicName, "View", "Dictionaries", new { Id = Model.DicId }, new { @class = "cyan" }),
  @(Model.IsDirect ? Resource._DirectDirection : Resource._InverseDirection)
</h2>

@Html.PageLinks(Model.PageInfo, "Dictionary", rv)
<div class="x-scroll">
  <table class='solid-table'>
    <tr>
      <th>
        @Html.ActionLink(Resource._NumberSign + rv.OrderSign(1), "Dictionary", "User", rv.Clone(1),
          null)
      </th>
      <th>
        @Html.ActionLink(Resource._Word + rv.OrderSign(2), "Dictionary", "User", rv.Clone(2),
          null)
      </th>
      <th>
        @Html.ActionLink(Resource._Translation + rv.OrderSign(3), "Dictionary", "User", rv.Clone(3),
          null)
      </th>
      <th>
        @Html.ActionLink("Status" + rv.OrderSign(4), "Dictionary", "User", rv.Clone(4),
          null)
      </th>
      @if (Model.IsOwner)
      {
        <th></th>}
    </tr>

    @{int count = Model.PageInfo.SkippedItems;}
    @foreach (var dr in Model.DicResults)
    {
      <tr @(dr.IsSkipped ? "class=grey" : "")>
        <td>
          @Html.ActionLink((++count).ToString(), "Edit", "Cards", new { Id = dr.Card.Id }, null)
        </td>
        <td class="align-left">
          @dr.Card.Word
          @if (dr.Card.Transcription != null)
          {<text>@dr.Card.Transcription</text>}
        </td>
        <td class="align-left">
          @dr.Card.Translation
        </td>
        <td class="align-left" data-skipped="Skipped" data-to-be-studied="To be studied">
          @if (dr.UpdatedCnt > 0)
          {
            <text>@Resource._Strength: </text>if (User.IsInRole("admin")) {
              @Html.ActionLink(dr.Strength.ToString("F4"), "edit", "results", new { id = dr.ResultId }, null)
            }
            else
            {@dr.Strength.ToString("F4")}
          }
          else
          {@(dr.IsSkipped ? Resource.pSkipped : Resource.pToBeStudied)}
        </td>
        @if (Model.IsOwner)
        {
          <td>
            <input type="checkbox" class="toggle-skip" data-id="@dr.Card.Id" data-is-direct="@Model.IsDirect" @(dr.IsSkipped ? "" : "checked") />
          </td>
        }
      </tr>
    }
  </table>
</div>
@Html.PageLinks(Model.PageInfo, "Dictionary", rv)

Apprendre/Views/User/Login.cshtml
@model Apprendre.Models.LoginVM

@{
  ViewBag.Title = Resource.uLogin;

}
<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("Login", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-login" }))
{
  @Html.AntiForgeryToken()
  @Html.ValidationSummary(true)
  <div>
    @Html.LabelFor(m => m.UserName, new { @class = "form-label" })
    @Html.TextBoxFor(m => m.UserName, new { @class = "form-input" })
    @Html.ValidationMessageFor(m => m.UserName)
  </div>
  <div>
    @Html.LabelFor(m => m.Password, new { @class = "form-label" })
    @Html.PasswordFor(m => m.Password, new { @class = "form-input" })
    @Html.ValidationMessageFor(m => m.Password)
  </div>
  <div>
        @Html.CheckBoxFor(m => m.RememberMe, new { style = "margin-top: 10px;" })
        @Html.LabelFor(m => m.RememberMe)
  </div>
  <input type="submit" class="margin-15 but" value="@Resource.uLogin" />
}
<p>@Html.Raw(Resource.uRegisterIfNoAccount.InsertLinksWithClass("bold cyan", Url.Action("Register")))</p>
<p>@Html.ActionLink(Resource.uIForgotPassword, "Reset_Password", null,  new {@class = "bold cyan"})</p>

@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
}

Apprendre/Views/User/ResetMessageSent.cshtml
@{
  ViewBag.Title = Resource.uMessageSent;
}

<h2>@ViewBag.Title</h2>

<p>@Resource.uMessageIsSent</p>

<p>@Html.Raw(Resource.uGoToHomepage.InsertLinksWithClass("bold cyan", Url.Action("Main", "Study")))</p>

Apprendre/Views/User/Reset_Password.cshtml
@model ResetPasswordVM
@{
  ViewBag.Title = Resource.uIForgotPassword;
}

<h1>@ViewBag.Title</h1>

<p>@Resource.uMessageWillBeSent</p>

@using (Html.BeginForm("Reset_Password", "User", FormMethod.Post, new { @class = "form-login" }))
{
  @Html.AntiForgeryToken()
  <div>
    @Html.LabelFor(m => m.Email, new { @class = "form-label" })
    @Html.TextBoxFor(m => m.Email, new { @class = "form-input" })
  </div>
  @Html.ValidationSummary(true)
  <input type="submit" class="margin-15 but" value="@Resource._Send" />
}

Apprendre/Views/User/Stat.cshtml
@model UserStatVM
@{
  ViewBag.Title = Resource.pStatisticsIn + " " + Model.DicName + ", " + (Model.IsDirect ? Resource._DirectDirection : Resource._InverseDirection);
}

@{ViewBag.Type = "stat";}
@Html.Partial("_UserNav")

<p class="info-message">@ViewBag.Message</p>

<div id="profile-container">
  @Html.Partial("_CurDicStatPartial", Model.DicStat)

  @if (Model.DicStat.Studied > 0)
  {
    <h2>@Resource.pStrengthChartTitle</h2>
    <div id="chart-ranks" data-count="@Resource.pChartCount" data-strength="@Resource._Strength"></div>

    <h2>@Resource.pTimeChartTitle</h2>
    <div id="chart-days" data-count="@Resource.pChartCount" data-days="@Resource.pChartDays"></div>

    <h2>@Resource.pTheWeakestWords</h2>
    <div class="x-scroll">
      <table class='solid-table'>
        <tr><th>@Resource._Word</th><th>@Resource._Translation</th><th>@Resource._Strength</th><th>@Resource.pCount_gen</th></tr>
        @foreach (var res in Model.WeakResults)
        {
          <tr>
            <td>@res.Card.Word</td>
            <td>@res.Card.Translation</td>
            <td>@res.Strength.Value.ToString("F2")</td>
            <td>@res.UpdatedCnt</td>
          </tr>
        }
      </table>
    </div>
    if (User.IsInRole("admin"))
    {
      using (Html.BeginForm("DeleteAll", "Results", FormMethod.Post, new { onSubmit = "return confirm('" + Resource.uDeleteStatConfirmation + "');" }))
      {
        @Html.Hidden("userId", Model.UserId);
        @Html.Hidden("dicId", Model.DicStat.DicId);
        @Html.Hidden("isDirect", Model.DicStat.IsDirect);
        <input type="submit" class="but margin-15" value="@Resource._Delete">
      }
    }
  }
</div>

@section Scripts {
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script>
    var ranks_data=@Html.Raw(Model.RanksData);
    var days_data=@Html.Raw(Model.DaysData);    
  </script>
}